name: Run Medium AI Agent Daily

on:
  schedule:
    - cron: '7 4 * * *'  # By 8:00 AM Romanian every day
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Download previous sent_messages.txt artifact if it exists
      - name: Download sent_messages artifact
        uses: actions/download-artifact@v4
        with:
          name: sent_messages
          path: ./  # downloads to root of repo
        continue-on-error: true  # don't fail if no artifact found

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run the script
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          RECIPIENT_EMAIL: ${{ secrets.RECIPIENT_EMAIL }}
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          SENDER_PASSWORD: ${{ secrets.SENDER_PASSWORD }}
          ACCUWEATHER_API_KEY: ${{ secrets.ACCUWEATHER_API_KEY }}
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
        run: python main.py

      # Upload the sent_messages.txt file as an artifact
      - name: Upload sent_messages artifact
        uses: actions/upload-artifact@v4
        with:
          name: sent_messages
          path: sent_messages.txt
